### ISSUE TITLE
GUI inputs failing to clear placeholder when selected

### ISSUE THREAD

**Issue by danielway** [jakedv24/senior-design-sdmay21-26#90]
Our GUI provides a placeholder indicating the range for each field, but this placeholder doesn't always clear when the field is selected.

**Comment by DaultonLeach** [comment]
Currently how we have it implemented, we do a small check to try and ensure the user hasn't entered data before clearing the text field. I think we have a small timing error somewhere. We could just assume the user is not misclicking and whenever they click a text field just clear it automatically.

**Comment by DaultonLeach** [comment]
Solution: Switch over the logic to a focus listener instead of a mouse click listener. Abstract this logic into a super type that we can call in order to refactor the code a bit. 

Ex Code:searchText = new JTextField("Search");
searchText.setForeground(Color.GRAY);
searchText.addFocusListener(new FocusListener() {
    @Override
    public void focusGained(FocusEvent e) {
        if (searchText.getText().equals("Search")) {
            searchText.setText("");
            searchText.setForeground(Color.BLACK);
        }
    }
    @Override
    public void focusLost(FocusEvent e) {
        if (searchText.getText().isEmpty()) {
            searchText.setForeground(Color.GRAY);
            searchText.setText("Search");
        }
    }
    });

Documentation: https://iastate.webex.com/iastate/url.php?gourl=https%3a%2f%2fstackoverflow%2ecom%2fquestions%2f16213836%2fjava%2dswing%2djtextfield%2dset%2dplaceholder

**Comment by DaultonLeach** [comment]
Fixed with PR 110
